name: Deploy to Ubuntu Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/deploy_key
      
      - name: Deploy to Server
        run: |
          ssh -v -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "\
            cd ${{ secrets.SERVER_DEPLOY_PATH }} && \
            git pull origin main && \
            npm install && \
            npm run build && \
            pm2 delete himchanhomecare || true && \  # 기존 프로세스 삭제
            pm2 start npm --name himchanhomecare -- start && \
            pm2 save"  # 상태 저장
